---
version: "2"

services:
  ipinfo:
    build:
      context: .
      args:
        MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
    image: ipinfo:local
    ports:
      - "127.0.0.1:8085:8080"
    restart: unless-stopped
