server {
    listen               8080 default_server;
    listen          [::]:8080 default_server;
    server_name                            _;
    add_header      X-Powered-By              "ipinfo.tw/github" always;

    add_header      Cache-Control                     "no-store" always;
    add_header      X-Frame-Options                 "SAMEORIGIN" always;
    add_header      X-XSS-Protection             "1; mode=block" always;
    add_header      X-Content-Type-Options             "nosniff" always;
    add_header      Referrer-Policy "no-referrer-when-downgrade" always;
    add_header      Content-Security-Policy "default-src 'none'; img-src 'self'" always;

    set $ip_country "$ip_country_code / $ip_country_name";
    set $ip_city    "$ip_city_name / $ip_subdivision_name";
    set $ip_as      "AS$ip_asn / $ip_aso";

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /robots.txt {
        log_not_found off;
        access_log off;
    }

    location = /github {
        return 301      https://github.com/ayaka14732/ipinfo;
    }
    location = /asn {
        return 200      "$ip_asn\n";
    }
    location = /as_desc {
        return 200      "$ip_aso\n";
    }
    location = /user_agent {
        return 200      "$http_user_agent\n";
    }
    location ~* ^/index.htm(l)?$ {
        rewrite ^(.*)$ /;
    }
    location = / {
        return 200      "$remote_addr\n$ip_city\n$ip_country\n$ip_as\n";
    }
    location = /json {
        default_type application/json;
        return 200 "{\"ip\":\"$remote_addr\",\"country_code\":\"$ip_country_code\",\"country_name\":\"$ip_country_name\",\"city_name\":\"$ip_city_name\",\"subdivision_code\":\"$ip_subdivision_code\",\"subdivision_name\":\"$ip_subdivision_name\",\"postal_code\":\"$ip_postal_code\",\"latitude\":\"$ip_latitude\",\"longitude\":\"$ip_longitude\",\"time_zone\":\"$ip_time_zone\",\"asn\":\"$ip_asn\",\"as_desc\":\"$ip_aso\",\"user_agent\":\"$http_user_agent\"}\n";
    }
    location = /build_epoch {
        default_type application/json;
        return 200 "{\"GeoLite2-Country\":\"$ip_country_build_epoch\",\"GeoLite2-City\":\"$ip_city_build_epoch\",\"GeoLite2-ASN\":\"$ip_as_build_epoch\"}\n";
    }

    location @404 {
        return 404 "404 not found. See https://github.com/ayaka14732/ipinfo \n";
    }
    error_page 404 = @404;

    access_log     /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;
}
